# Generated by Django 3.1.7 on 2021-04-05 14:29

from django.db import migrations, models
import news_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to=news_setting.models.upload_image_path, verbose_name='تصویر لوگو')),
                ('larger_image', models.ImageField(upload_to=news_setting.models.upload_image_path, verbose_name='تصویر بزرگ')),
                ('little_image_first', models.ImageField(upload_to=news_setting.models.upload_image_path, verbose_name='تصویر کوچک ۱')),
                ('little_image_second', models.ImageField(upload_to=news_setting.models.upload_image_path, verbose_name='تصویر کوچک ۲')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
