# Generated by Django 3.1.7 on 2021-04-06 14:19

from django.db import migrations, models
import news_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_img', models.ImageField(upload_to=news_setting.models.upload_image_path, verbose_name='تصویر درباره ما')),
                ('about_text', models.TextField(verbose_name='متن درباره ما')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
