# Generated by Django 3.1.7 on 2021-04-11 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import news_account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0, verbose_name='سن کاربر')),
                ('image', models.ImageField(default='default.jpg', upload_to=news_account.models.upload_image_path, verbose_name='تصویر کاربر')),
                ('education', models.CharField(default='کارشناسی', max_length=30, verbose_name='تحصیلات کاربر')),
                ('date_added', django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2021, 4, 11, 21, 51, 23, 241247), null=True, verbose_name='تاریخ ثبت نام کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعات کاربر',
                'verbose_name_plural': 'اطلاعات کاربران',
            },
        ),
    ]
