# Generated by Django 3.1.7 on 2021-04-13 05:03

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_account', '0004_auto_20210413_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2021, 4, 13, 9, 32, 59, 833126), null=True, verbose_name='تاریخ ثبت نام کاربر'),
        ),
    ]
