# Generated by Django 3.1.7 on 2021-04-13 06:29

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_account', '0005_auto_20210413_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'ordering': ['-date_added'], 'verbose_name': 'اطلاعات کاربر', 'verbose_name_plural': 'اطلاعات کاربران'},
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2021, 4, 13, 10, 58, 44, 232398), null=True, verbose_name='تاریخ ثبت نام کاربر'),
        ),
    ]
