# Generated by Django 3.1.7 on 2021-04-16 08:02

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_account', '0006_auto_20210413_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 12, 32, 13, 205006), null=True, verbose_name='تاریخ ثبت نام کاربر'),
        ),
    ]
