# Generated by Django 3.1.7 on 2021-04-16 10:27

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_account', '0009_auto_20210416_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 14, 57, 40, 821626), null=True, verbose_name='تاریخ ثبت نام کاربر'),
        ),
    ]
