# Generated by Django 3.1.7 on 2021-04-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_contact', '0002_auto_20210406_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='full_name',
        ),
    ]
