# Generated by Django 3.1.7 on 2021-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_contact', '0003_auto_20210406_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='ایمیل'),
        ),
    ]
