# Generated by Django 3.1.7 on 2021-04-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import news_blog_post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خبر',
                'verbose_name_plural': 'دسته\u200cبندی خبرها',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=news_blog_post.models.upload_image_path, verbose_name='تصویر خبر')),
            ],
            options={
                'verbose_name': 'تصویر خبر',
                'verbose_name_plural': 'تصاویر خبرها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خبر')),
                ('content', models.TextField(verbose_name='متن خبر')),
                ('date_added', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد خبر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منتشر کننده خبر')),
                ('image', models.ManyToManyField(blank=True, null=True, to='news_blog_post.PostImage', verbose_name='تصویر خبر')),
            ],
            options={
                'verbose_name': 'خبر جدید',
                'verbose_name_plural': 'خبرها',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Comment_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام\u200cخانوادگی')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('date_added', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ایجاد نظر')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog_post.post', verbose_name='خبر مربوطه')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
            },
        ),
    ]
