# Generated by Django 3.1.7 on 2021-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories_post',
            field=models.ManyToManyField(blank=True, null=True, to='news_blog_post.PostCategory', verbose_name='دسته بندی خبر'),
        ),
    ]
