# Generated by Django 3.1.7 on 2021-04-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0002_post_categories_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_post',
            options={'ordering': ['is_read'], 'verbose_name': 'نظر کاربر', 'verbose_name_plural': 'نظرات کاربران'},
        ),
        migrations.AddField(
            model_name='comment_post',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
