# Generated by Django 3.1.7 on 2021-04-13 04:36

from django.db import migrations, models
import django.db.models.deletion
import news_blog_post.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0007_auto_20210413_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=news_blog_post.models.upload_image_path, verbose_name='تصویر خبر ۱'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=news_blog_post.models.upload_image_path, verbose_name='تصویر خبر ۲'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_blog_post.postcategory', verbose_name='دسته بندی خبر'),
        ),
    ]
