# Generated by Django 3.1.7 on 2021-04-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0008_auto_20210413_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_blog_post.postcategory', verbose_name='دسته بندی خبر'),
        ),
    ]
