# Generated by Django 3.1.7 on 2021-04-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0009_auto_20210413_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_blog_post.postimage', verbose_name='تصویر خبر'),
        ),
    ]
