# Generated by Django 3.1.7 on 2021-04-13 06:29

import datetime
from django.db import migrations, models
import django_jalali.db.models
import news_blog_post.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0010_auto_20210413_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 4, 13, 10, 58, 44, 236783), verbose_name='تاریخ ایجاد خبر'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_1',
            field=models.ImageField(upload_to=news_blog_post.models.upload_image_path, verbose_name='تصویر خبر ۱'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_2',
            field=models.ImageField(upload_to=news_blog_post.models.upload_image_path, verbose_name='تصویر خبر ۲'),
        ),
    ]
