# Generated by Django 3.1.7 on 2021-04-16 08:02

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0011_auto_20210413_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_count',
            field=models.IntegerField(default=0, verbose_name='تعداد نپسندها'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='تعداد پسندها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 4, 16, 12, 32, 13, 209280), verbose_name='تاریخ ایجاد خبر'),
        ),
    ]
