# Generated by Django 3.1.7 on 2021-04-16 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0012_auto_20210416_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 4, 16, 12, 42, 32, 894060), verbose_name='تاریخ ایجاد خبر'),
        ),
        migrations.CreateModel(
            name='VisitedIpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(verbose_name='آدرس\u200cها')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog_post.post', verbose_name='خبر مربوطه')),
            ],
            options={
                'verbose_name': 'آدرس ip کاربر',
                'verbose_name_plural': 'آدرس ip کاربر',
            },
        ),
    ]
