# Generated by Django 3.1.7 on 2021-04-16 08:23

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog_post', '0013_auto_20210416_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedippost',
            name='value',
            field=models.BooleanField(default=False, verbose_name='نظر ثبت شده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2021, 4, 16, 12, 53, 2, 977030), verbose_name='تاریخ ایجاد خبر'),
        ),
    ]
